# Change format of zoorvival datasets to be more uniform with the one from the original code

get the datasets and create new csv with a similar format

In [1]:
import os
import numpy as np
import pandas as pd
import copy

In [2]:
# get the whole data
study = 'BRCA'
direction = 'src/datasets_csv'

# clinical
clinical = pd.read_csv(
    os.path.join(f'{study}', f'{study}_clinical_preprocessed.csv'), 
    index_col=0
)

# omic 1 2 3 4
omic_cnv = pd.read_csv(
    os.path.join(f'{study}', f'{study}_CNV_filtered.csv'),    # all rna data
    engine='python', 
    index_col=0
)

omic_dna = pd.read_csv(
    os.path.join(f'{study}', f'{study}_DNAm_filtered.csv'),    # all rna data
    engine='python', 
    index_col=0
)

omic_mirna = pd.read_csv(
    os.path.join(f'{study}', f'{study}_miRNA_filtered.csv'),    # all rna data
    engine='python', 
    index_col=0
)

omic_mrna = pd.read_csv(
    os.path.join(f'{study}', f'{study}_mRNA_filtered.csv'),    # all rna data
    engine='python', 
    index_col=0
)

In [3]:
clinical.head(3)

,age,ajcc_metastasis_pathologic_pm,ajcc_nodes_pathologic_pn,ajcc_pathologic_tumor_stage,ajcc_staging_edition,ajcc_tumor_pathologic_pt,brachytherapy_total_dose_point_a,cent17_copy_number,days_to_initial_pathologic_diagnosis,dfs_time,...,sample_count,sex,site_of_tumor_tissue,staging_system,staging_system_other,surgery_for_positive_margins,surgery_for_positive_margins_other,surgical_procedure_first,tissue_source_site,tumor_status
patient_id,,,,,,,,,,,,,,,,,,,,,
4H-AAAK,50.0,M0,N2a,Stage IIIA,7th,T2,NaN,NaN,0.0,11.43,...,1,Female,Breast,Axillary lymph node dissection alone,NaN,NaN,NaN,Modified Radical Mastectomy,4H,TUMOR FREE
5L-AAT0,42.0,M0,N0,Stage IIA,7th,T2,NaN,NaN,0.0,48.52,...,1,Female,Breast,Axillary lymph node dissection alone,NaN,NaN,NaN,Modified Radical Mastectomy,5L,TUMOR FREE
5T-A9QA,52.0,MX,NX,Stage IIA,7th,T2,NaN,NaN,0.0,9.95,...,1,Female,Breast,No axillary staging,NaN,NaN,NaN,NaN,5T,NaN

start with clinical_data and label_data

patient_id --> case_id; consider to add TCGA- to the id

CLINICAL:

stage:
ajcc_pathologic_tumor_stage --> stage; from STAGE nstage to nstage

subtype:
add 'LUAC' everywhere

grade:
ajcc_staging_edition --> grade    (????)

LABEL:

case_id:
as above

slide_id:
the case_id is enought to find the slide_id, add some 'X' to have a similar format as the other data

age:
age --> age

site:
primary_site_patient --> site    (?????)

survival_months, survival_months_dss, survival_months_pfi:
dfs_time --> survival anything
os_time

censorship, censorship_dss, censorship_pfi:
dfs_event --> censorship anything    <<<<< need to change to 1- censorship??? >>>>>
os_event

\#\#\# disease-free survival (DFS); overall survival (OS); disease-specific survival(DSS), disease-free interval (DFI); progression-freeinterval (PFI)

is_female:
sex --> is_female;   Female/Male to 1.0/0.0

oncotree_code:
same as subtype in clinical_data

train:
???????

everything else can go into 'clinical_data', isn't going to be used

## LABEL_DATA

In [4]:
def to_case_id(patient):
    case_id = 'TCGA-' + patient
    return case_id

def to_slide_id(patient, other_patient_id):
    slide_id = 'TCGA-' + patient + '-XXX-XX-XXX.' + other_patient_id + '.svs'
    return slide_id

def to_is_female(sex):
    out = 0
    if sex == 'Female':
        out = 1
    return out

In [5]:
# create label_data
used_columns = []
# case_id, slide_id
label = pd.DataFrame()
label['case_id'] = clinical.index
label['case_id'] = to_case_id(label['case_id'].values)

label['slide_id'] = to_slide_id(clinical.index.values, clinical['other_patient_id'].values)

# age
label['age'] = clinical['age'].values
used_columns.append('age')

# site
where = 'tissue_source_site'
if study in ['LUAD', 'BLCA', 'BRCA']:
    where = 'primary_site_patient'
label['site'] = clinical[where].values
used_columns.append(where)

# censorship
label['censorship_dfs'] = 1- clinical['dfs_event'].values
label['censorship_os'] = 1- clinical['os_event'].values

label['survival_months_dfs'] = clinical['dfs_time'].values
label['survival_months_os'] = clinical['os_time'].values

used_columns.append('dfs_event')
used_columns.append('os_event')
used_columns.append('dfs_time')
used_columns.append('os_time')

# is_female
label['is_female'] = [to_is_female(x) for x in clinical['sex'].values]
used_columns.append('sex')

label['oncotree_code'] = f'{study}'

label['train'] = 1.0

print(label[:3])

        case_id                                           slide_id   age  \
0  TCGA-4H-AAAK  TCGA-4H-AAAK-XXX-XX-XXX.6623FC5E-00BE-4476-967...  50.0
1  TCGA-5L-AAT0  TCGA-5L-AAT0-XXX-XX-XXX.86C6F993-327F-4525-998...  42.0
2  TCGA-5T-A9QA  TCGA-5T-A9QA-XXX-XX-XXX.2FD36838-5A83-433E-AC8...  52.0

                               site  censorship_dfs  censorship_os  \
0    Left|Left Upper Outer Quadrant             1.0              1
1  Right|Right Lower Outer Quadrant             1.0              1
2                              Left             1.0              1

   survival_months_dfs  survival_months_os  is_female oncotree_code  train
0                11.43               11.43          1          BRCA    1.0
1                48.52               48.52          1          BRCA    1.0
2                 9.95                9.95          1          BRCA    1.0

In [6]:
# clean it a bit? eliminate the na?
for col in label.columns:
    print(col)
    df1 = label[label[col].isna()]
    print('num of missing rows: ', df1.shape[0])
    print(df1[col])

case_id
num of missing rows:  0
Series([], Name: case_id, dtype: object)
slide_id
num of missing rows:  0
Series([], Name: slide_id, dtype: object)
age
num of missing rows:  1
977   NaN
Name: age, dtype: float64
site
num of missing rows:  0
Series([], Name: site, dtype: object)
censorship_dfs
num of missing rows:  83
13     NaN
24     NaN
41     NaN
45     NaN
47     NaN
        ..
838    NaN
857    NaN
966    NaN
980    NaN
1004   NaN
Name: censorship_dfs, Length: 83, dtype: float64
censorship_os
num of missing rows:  0
Series([], Name: censorship_os, dtype: int64)
survival_months_dfs
num of missing rows:  84
13     NaN
24     NaN
41     NaN
45     NaN
47     NaN
        ..
857    NaN
966    NaN
977    NaN
980    NaN
1004   NaN
Name: survival_months_dfs, Length: 84, dtype: float64
survival_months_os
num of missing rows:  1
857   NaN
Name: survival_months_os, dtype: float64
is_female
num of missing rows:  0
Series([], Name: is_female, dtype: int64)
oncotree_code
num of missing rows:  0
Series([], Name: oncotree_code, dtype: object)
train
num of missing rows:  0
Series([], Name: train, dtype: float64)

there are 69 rows with missing dfs_censorship, 73 of missing survival_months. For os: 0 censorship, 8 for survival_months. Suggested to use os to calculate survival analysis

In [7]:
# remove na rows from os
print('before:') 
print(label.shape)
label = label.dropna(subset=['censorship_os', 'survival_months_os'])
print('after: ')
print(label.shape)
print(label[label['censorship_os'].isna()])
print(label[label['survival_months_os'].isna()])

if 'Unnamed: 0' in label.columns:
    label = label.drop(columns=['Unnamed: 0'])
    print('dropped')

before:
(1012, 11)
after:
(1011, 11)
Empty DataFrame
Columns: [case_id, slide_id, age, site, censorship_dfs, censorship_os, survival_months_dfs, survival_months_os, is_female, oncotree_code, train]
Index: []
Empty DataFrame
Columns: [case_id, slide_id, age, site, censorship_dfs, censorship_os, survival_months_dfs, survival_months_os, is_female, oncotree_code, train]
Index: []

In [8]:
# save the new csv
label_folder = direction + f'/metadata/tcga_{study}.csv'
label.to_csv(f'{label_folder}')

## CLINICAL_DATA

In [9]:
def to_stage(stage):
    # remove 'Stage '
    stage = [str(txt).replace('Stage ', '') for txt in stage.values]
    return stage

In [10]:
clinical_data = pd.DataFrame()
clinical_data['case_id'] = to_case_id(clinical.index.values)

# stage
where = 'clinical_stage'
if study in ['LUAD', 'BLCA', 'BRCA']:
    where = 'ajcc_pathologic_tumor_stage'
clinical_data['stage'] = to_stage(clinical[where])
used_columns.append(where)

# subtype
clinical_data['subtype'] = f'{study}'

clinical_data['grade'] = clinical['ajcc_staging_edition'].values
used_columns.append('ajcc_staging_edition')

print(clinical_data[:3])

# add all the other columns
for col in clinical.columns:
    if col not in used_columns:
        clinical_data[col + '+'] = clinical[col].values

if 'Unnamed: 0' in clinical_data.columns:
    clinical_data = clinical_data.drop(columns=['Unnamed: 0'])
    print('dropped')
    
print(clinical_data[:3])

        case_id stage subtype grade
0  TCGA-4H-AAAK  IIIA    BRCA   7th
1  TCGA-5L-AAT0   IIA    BRCA   7th
2  TCGA-5T-A9QA   IIA    BRCA   7th
        case_id stage subtype grade ajcc_metastasis_pathologic_pm+  \
0  TCGA-4H-AAAK  IIIA    BRCA   7th                             M0
1  TCGA-5L-AAT0   IIA    BRCA   7th                             M0
2  TCGA-5T-A9QA   IIA    BRCA   7th                             MX

  ajcc_nodes_pathologic_pn+ ajcc_tumor_pathologic_pt+  \
0                       N2a                        T2
1                        N0                        T2
2                        NX                        T2

  brachytherapy_total_dose_point_a+ cent17_copy_number+  \
0                               NaN                 NaN
1                               NaN                 NaN
2                               NaN                 NaN

   days_to_initial_pathologic_diagnosis+  ... retrospective_collection+  \
0                                    0.0  ...                        NO
1                                    0.0  ...                       YES
2                                    0.0  ...                        NO

  sample_count+ site_of_tumor_tissue+                       staging_system+  \
0             1                Breast  Axillary lymph node dissection alone
1             1                Breast  Axillary lymph node dissection alone
2             1                Breast                   No axillary staging

  staging_system_other+ surgery_for_positive_margins+  \
0                   NaN                           NaN
1                   NaN                           NaN
2                   NaN                           NaN

  surgery_for_positive_margins_other+    surgical_procedure_first+  \
0                                 NaN  Modified Radical Mastectomy
1                                 NaN  Modified Radical Mastectomy
2                                 NaN                          NaN

  tissue_source_site+  tumor_status+
0                  4H     TUMOR FREE
1                  5L     TUMOR FREE
2                  5T            NaN

[3 rows x 84 columns]

In [11]:
# save the new csv
clinical_folder = direction + f'/clinical_data/tcga_{study}_clinical.csv'
clinical_data.to_csv(f'{clinical_folder}')

## OMICS DATA

the idea is to put them all together in a single csv, creating a 'signature' file where we include the attributes of each cathegory

In [12]:
def find_na(df):
    print('columns')
    num_col = 0
    for col in df.columns:
        df1 = df[df[col].isna()]
        if df1.shape[0] > 0:
            print(col)
            print('num of missing rows: ', df1.shape[0])
            print(df1[col])
            num_col += 1
    print('num of column with na: ', num_col)
    
    print('patients')
    nan_rows = df[df.isnull().T.any()]
    print('size: ', nan_rows.shape[0])
    print(nan_rows)

In [13]:
print('\nCNV')
find_na(omic_cnv)
print('\nDNA')
find_na(omic_dna)
print('\nmiRNA')
find_na(omic_mirna)
print('\nmRNA')
find_na(omic_mrna)

CNV
columns
num of column with na:  0
patients
size:  0
Empty DataFrame
Columns: [ENSG00000140798, ENSG00000261017, ENSG00000288026, ENSG00000260450, ENSG00000261538, ENSG00000261325, ENSG00000288601, ENSG00000261725, ENSG00000260889, ENSG00000261231, ENSG00000222268, ENSG00000262038, ENSG00000260497, ENSG00000121270, ENSG00000260782, ENSG00000155330, ENSG00000260281, ENSG00000222767, ENSG00000259983, ENSG00000259821, ENSG00000261173, ENSG00000069345, ENSG00000166123, ENSG00000140795, ENSG00000260086, ENSG00000260726, ENSG00000222170, ENSG00000260184, ENSG00000171208, ENSG00000259866, ENSG00000261336, ENSG00000259918, ENSG00000102910, ENSG00000279509, ENSG00000260744, ENSG00000261369, ENSG00000102893, ENSG00000260012, ENSG00000239840, ENSG00000129636, ENSG00000260347, ENSG00000275909, ENSG00000261802, ENSG00000260688, ENSG00000091651, ENSG00000069329, ENSG00000280376, ENSG00000261239, ENSG00000272545, ENSG00000260067, ENSG00000196470, ENSG00000171241, ENSG00000261131, ENSG00000260909, ENSG00000261512, ENSG00000259856, ENSG00000199448, ENSG00000261356, ENSG00000260251, ENSG00000260052, ENSG00000280067, ENSG00000240793, ENSG00000261267, ENSG00000102921, ENSG00000280131, ENSG00000260024, ENSG00000287469, ENSG00000261421, ENSG00000243609, ENSG00000260033, ENSG00000259912, ENSG00000261393, ENSG00000261092, ENSG00000102935, ENSG00000261815, ENSG00000274969, ENSG00000166164, ENSG00000275155, ENSG00000259978, ENSG00000260089, ENSG00000263110, ENSG00000262950, ENSG00000261623, ENSG00000260249, ENSG00000270120, ENSG00000167207, ENSG00000167208, ENSG00000121281, ENSG00000102924, ENSG00000261703, ENSG00000279249, ENSG00000280189, ENSG00000279842, ENSG00000261644, ENSG00000264947, ENSG00000083799, ENSG00000166152, ENSG00000260029, ENSG00000205414, ENSG00000278909, ...]
Index: []

[0 rows x 4096 columns]

DNA
columns
cg22318304
num of missing rows:  8
patient_id
A7-A13D   NaN
AO-A0JA   NaN
AR-A1AJ   NaN
AR-A1AV   NaN
B6-A0RG   NaN
B6-A0RL   NaN
BH-A0DD   NaN
BH-A0HY   NaN
Name: cg22318304, dtype: float64
cg06377278
num of missing rows:  1
patient_id
B6-A0RH   NaN
Name: cg06377278, dtype: float64
cg22879515
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg22879515, dtype: float64
cg21634602
num of missing rows:  15
patient_id
A7-A13E   NaN
AO-A03N   NaN
AO-A03U   NaN
AO-A0JB   NaN
AO-A0JF   NaN
AO-A0JL   NaN
AO-A124   NaN
AO-A129   NaN
B6-A0RE   NaN
BH-A0B9   NaN
BH-A0C0   NaN
BH-A0E0   NaN
BH-A0E2   NaN
BH-A0H9   NaN
BH-A0WA   NaN
Name: cg21634602, dtype: float64
cg01697732
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg01697732, dtype: float64
cg03168582
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg03168582, dtype: float64
cg18349835
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg18349835, dtype: float64
cg18815943
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg18815943, dtype: float64
cg10775273
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg10775273, dtype: float64
cg15042080
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg15042080, dtype: float64
cg25908985
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg25908985, dtype: float64
cg18335243
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg18335243, dtype: float64
cg00756058
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg00756058, dtype: float64
cg12005098
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg12005098, dtype: float64
cg25361844
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg25361844, dtype: float64
cg14998713
num of missing rows:  5
patient_id
AR-A0TV   NaN
AR-A1AV   NaN
BH-A0B8   NaN
BH-A1FM   NaN
E2-A9RU   NaN
Name: cg14998713, dtype: float64
cg24358465
num of missing rows:  3
patient_id
B6-A0WX   NaN
C8-A134   NaN
D8-A1JH   NaN
Name: cg24358465, dtype: float64
cg15613048
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg15613048, dtype: float64
cg02085507
num of missing rows:  2
patient_id
C8-A12Q   NaN
D8-A1JH   NaN
Name: cg02085507, dtype: float64
cg05937453
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg05937453, dtype: float64
cg25917510
num of missing rows:  1
patient_id
E2-A1L6   NaN
Name: cg25917510, dtype: float64
cg19850348
num of missing rows:  2
patient_id
B6-A0RH   NaN
C8-A134   NaN
Name: cg19850348, dtype: float64
cg01216369
num of missing rows:  24
patient_id
A2-A04W   NaN
A7-A5ZX   NaN
A8-A06R   NaN
A8-A08J   NaN
AR-A0U2   NaN
AR-A1AH   NaN
B6-A0IE   NaN
B6-A0IH   NaN
B6-A0RH   NaN
B6-A0WX   NaN
BH-A0AV   NaN
BH-A18L   NaN
BH-A18U   NaN
C8-A12P   NaN
C8-A12Y   NaN
C8-A131   NaN
C8-A134   NaN
D8-A1JH   NaN
E2-A14Q   NaN
E2-A14W   NaN
E2-A153   NaN
E2-A15C   NaN
E2-A15O   NaN
E2-A1L6   NaN
Name: cg01216369, dtype: float64
cg05022306
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg05022306, dtype: float64
cg08914623
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg08914623, dtype: float64
cg12331389
num of missing rows:  1
patient_id
B6-A0RH   NaN
Name: cg12331389, dtype: float64
cg17872757
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg17872757, dtype: float64
cg12717594
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg12717594, dtype: float64
cg23887396
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg23887396, dtype: float64
cg08585897
num of missing rows:  37
patient_id
A1-A0SK   NaN
A2-A04R   NaN
A2-A0T0   NaN
A2-A0T2   NaN
A2-A0T4   NaN
A2-A0YH   NaN
A2-A0YK   NaN
A2-A3XT   NaN
A7-A13D   NaN
A7-A4SE   NaN
A8-A075   NaN
AC-A3HN   NaN
AC-A62X   NaN
AN-A0XO   NaN
AN-A0XP   NaN
AN-A0XS   NaN
AO-A0JD   NaN
AO-A0JI   NaN
AO-A124   NaN
AO-A125   NaN
AQ-A54N   NaN
AR-A0TT   NaN
AR-A0U2   NaN
AR-A0U3   NaN
B6-A0RE   NaN
B6-A0RI   NaN
B6-A0RM   NaN
B6-A0WV   NaN
B6-A0WY   NaN
BH-A0DS   NaN
BH-A0E2   NaN
BH-A0GY   NaN
BH-A0WA   NaN
BH-A1ET   NaN
C8-A1HG   NaN
C8-A1HN   NaN
E2-A574   NaN
Name: cg08585897, dtype: float64
cg25438963
num of missing rows:  1
patient_id
AC-A6IX   NaN
Name: cg25438963, dtype: float64
cg17838026
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg17838026, dtype: float64
cg12259256
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg12259256, dtype: float64
cg04797323
num of missing rows:  2
patient_id
C8-A134   NaN
D8-A1JH   NaN
Name: cg04797323, dtype: float64
cg08690031
num of missing rows:  9
patient_id
5T-A9QA   NaN
A7-A13E   NaN
AC-A6IX   NaN
AR-A1AJ   NaN
AR-A1AV   NaN
BH-A0E2   NaN
D8-A1JH   NaN
D8-A1Y3   NaN
E9-A1RC   NaN
Name: cg08690031, dtype: float64
cg17178336
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg17178336, dtype: float64
cg13755070
num of missing rows:  40
patient_id
3C-AALI   NaN
A1-A0SP   NaN
A2-A0T3   NaN
A2-A0T4   NaN
A2-A0YK   NaN
A2-A3XX   NaN
A7-A0DC   NaN
A8-A093   NaN
A8-A09E   NaN
A8-A0AB   NaN
AC-A6IX   NaN
AO-A03O   NaN
AO-A03V   NaN
AO-A0JL   NaN
AO-A124   NaN
AR-A1AJ   NaN
AR-A1AW   NaN
B6-A0IK   NaN
B6-A0RG   NaN
B6-A0RH   NaN
BH-A0E0   NaN
BH-A0HF   NaN
BH-A0WA   NaN
BH-A18L   NaN
BH-A18N   NaN
BH-A18P   NaN
BH-A1EW   NaN
C8-A12U   NaN
C8-A133   NaN
D8-A13Y   NaN
E2-A10A   NaN
E2-A10E   NaN
E2-A14O   NaN
E2-A14Y   NaN
E2-A154   NaN
E2-A155   NaN
E2-A15T   NaN
E2-A1B5   NaN
E2-A56Z   NaN
E2-A9RU   NaN
Name: cg13755070, dtype: float64
cg25156443
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg25156443, dtype: float64
cg02126753
num of missing rows:  1
patient_id
C8-A133   NaN
Name: cg02126753, dtype: float64
cg17095936
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg17095936, dtype: float64
cg16994506
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg16994506, dtype: float64
cg06043114
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg06043114, dtype: float64
cg10296238
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg10296238, dtype: float64
cg05822532
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg05822532, dtype: float64
cg19560210
num of missing rows:  1
patient_id
C8-A133   NaN
Name: cg19560210, dtype: float64
cg26113512
num of missing rows:  1
patient_id
BH-A1FM   NaN
Name: cg26113512, dtype: float64
cg00679738
num of missing rows:  1
patient_id
B6-A0RH   NaN
Name: cg00679738, dtype: float64
cg22029275
num of missing rows:  4
patient_id
A8-A0AD   NaN
AC-A6IX   NaN
AO-A0JL   NaN
BH-A0H0   NaN
Name: cg22029275, dtype: float64
cg16509658
num of missing rows:  3
patient_id
BH-A0DD   NaN
C8-A134   NaN
D8-A1JH   NaN
Name: cg16509658, dtype: float64
cg17619823
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg17619823, dtype: float64
cg21176048
num of missing rows:  1
patient_id
AR-A1AV   NaN
Name: cg21176048, dtype: float64
cg13834567
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg13834567, dtype: float64
cg16319578
num of missing rows:  4
patient_id
A8-A08O   NaN
AC-A6IX   NaN
BH-A0BJ   NaN
D8-A73X   NaN
Name: cg16319578, dtype: float64
cg23129478
num of missing rows:  8
patient_id
A2-A0YG   NaN
A2-A0YH   NaN
A2-A0YK   NaN
B6-A0RH   NaN
BH-A0WA   NaN
C8-A130   NaN
C8-A134   NaN
E2-A15G   NaN
Name: cg23129478, dtype: float64
cg18671950
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg18671950, dtype: float64
cg13643585
num of missing rows:  1
patient_id
AC-A6IX   NaN
Name: cg13643585, dtype: float64
cg21250296
num of missing rows:  3
patient_id
AR-A1AN   NaN
B6-A0WX   NaN
C8-A134   NaN
Name: cg21250296, dtype: float64
cg01805540
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg01805540, dtype: float64
cg23113963
num of missing rows:  18
patient_id
A2-A0T4   NaN
A2-A0YK   NaN
A2-A1FW   NaN
A8-A09C   NaN
AN-A0XP   NaN
AO-A125   NaN
AR-A0TT   NaN
B6-A0RN   NaN
B6-A0WV   NaN
B6-A0X4   NaN
BH-A18G   NaN
BH-A1FL   NaN
C8-A12Z   NaN
C8-A137   NaN
D8-A143   NaN
D8-A1XR   NaN
E2-A14Y   NaN
E2-A15P   NaN
Name: cg23113963, dtype: float64
cg17371081
num of missing rows:  1
patient_id
AC-A6IX   NaN
Name: cg17371081, dtype: float64
cg21842478
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg21842478, dtype: float64
cg08085267
num of missing rows:  24
patient_id
A2-A0EW   NaN
A2-A0YK   NaN
A2-A1FW   NaN
A8-A07I   NaN
AN-A0FT   NaN
AO-A03V   NaN
AR-A0TY   NaN
AR-A1AH   NaN
B6-A0RH   NaN
BH-A0AY   NaN
BH-A0B0   NaN
BH-A0BR   NaN
BH-A0DZ   NaN
BH-A0W7   NaN
BH-A18P   NaN
C8-A12M   NaN
C8-A12U   NaN
C8-A12X   NaN
C8-A133   NaN
C8-A134   NaN
D8-A13Y   NaN
E2-A14Q   NaN
E2-A14S   NaN
E2-A14Y   NaN
Name: cg08085267, dtype: float64
cg02128567
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg02128567, dtype: float64
cg15271616
num of missing rows:  16
patient_id
A2-A0EU   NaN
A2-A0SV   NaN
AR-A0TV   NaN
AR-A1AJ   NaN
B6-A0RH   NaN
B6-A0RO   NaN
BH-A0AU   NaN
BH-A0B8   NaN
BH-A0BF   NaN
BH-A209   NaN
C8-A1HN   NaN
D8-A1Y3   NaN
E9-A1N3   NaN
E9-A1RC   NaN
E9-A1RF   NaN
E9-A226   NaN
Name: cg15271616, dtype: float64
cg12738197
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg12738197, dtype: float64
cg08348496
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg08348496, dtype: float64
cg14826683
num of missing rows:  11
patient_id
A2-A04W   NaN
A2-A0EW   NaN
B6-A0RH   NaN
BH-A18J   NaN
C8-A12U   NaN
C8-A130   NaN
C8-A133   NaN
E2-A14W   NaN
E2-A14Y   NaN
E9-A1N3   NaN
E9-A1RD   NaN
Name: cg14826683, dtype: float64
cg21922574
num of missing rows:  1
patient_id
AR-A24X   NaN
Name: cg21922574, dtype: float64
cg03127334
num of missing rows:  4
patient_id
A2-A0CW   NaN
C8-A134   NaN
E2-A10C   NaN
E2-A15F   NaN
Name: cg03127334, dtype: float64
cg13097407
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg13097407, dtype: float64
cg16786703
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg16786703, dtype: float64
cg27090216
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg27090216, dtype: float64
cg09230646
num of missing rows:  26
patient_id
A8-A086   NaN
A8-A08L   NaN
AN-A0XP   NaN
AR-A1AH   NaN
B6-A0IH   NaN
B6-A0RH   NaN
B6-A0X0   NaN
BH-A0C7   NaN
BH-A0DT   NaN
BH-A0W7   NaN
BH-A18L   NaN
BH-A18P   NaN
BH-A1EV   NaN
C8-A12N   NaN
C8-A12Y   NaN
C8-A130   NaN
C8-A134   NaN
C8-A138   NaN
E2-A10A   NaN
E2-A14S   NaN
E2-A14W   NaN
E2-A153   NaN
E2-A15C   NaN
E2-A15L   NaN
E2-A15R   NaN
E2-A15S   NaN
Name: cg09230646, dtype: float64
cg12406559
num of missing rows:  2
patient_id
BH-A0WA   NaN
C8-A134   NaN
Name: cg12406559, dtype: float64
cg22619018
num of missing rows:  6
patient_id
A1-A0SK   NaN
BH-A0BT   NaN
BH-A0H0   NaN
BH-A0H7   NaN
BH-A0WA   NaN
C8-A134   NaN
Name: cg22619018, dtype: float64
cg14046986
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg14046986, dtype: float64
cg27352063
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg27352063, dtype: float64
cg11934695
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg11934695, dtype: float64
cg16924616
num of missing rows:  20
patient_id
A1-A0SM   NaN
A2-A0SU   NaN
A2-A0SX   NaN
A2-A0YM   NaN
A2-A3XX   NaN
A7-A13E   NaN
A8-A08O   NaN
AN-A0XU   NaN
AO-A0JI   NaN
AO-A0JL   NaN
AO-A128   NaN
AO-A12B   NaN
AR-A0TP   NaN
B6-A0IK   NaN
B6-A0RI   NaN
B6-A0X4   NaN
BH-A0B9   NaN
BH-A0HY   NaN
BH-A0WA   NaN
E2-A106   NaN
Name: cg16924616, dtype: float64
cg08958015
num of missing rows:  1
patient_id
BH-A0E2   NaN
Name: cg08958015, dtype: float64
cg11648289
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg11648289, dtype: float64
cg25096582
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg25096582, dtype: float64
cg04424621
num of missing rows:  5
patient_id
A2-A0EW   NaN
AC-A23H   NaN
BH-A0DE   NaN
E2-A153   NaN
E2-A15F   NaN
Name: cg04424621, dtype: float64
cg00995327
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg00995327, dtype: float64
cg25875213
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg25875213, dtype: float64
cg15873301
num of missing rows:  3
patient_id
AR-A0TP   NaN
BH-A0E0   NaN
BH-A0WA   NaN
Name: cg15873301, dtype: float64
cg01637734
num of missing rows:  47
patient_id
A2-A04N   NaN
A2-A04U   NaN
A2-A04W   NaN
A2-A0CL   NaN
A2-A0EW   NaN
A2-A0T3   NaN
A7-A4SA   NaN
AN-A0FS   NaN
AN-A0XP   NaN
AN-A0XS   NaN
AN-A0XW   NaN
AR-A0U3   NaN
B6-A0WS   NaN
B6-A0WV   NaN
BH-A0B7   NaN
BH-A0BO   NaN
BH-A0C7   NaN
BH-A0DD   NaN
BH-A0DH   NaN
BH-A0DX   NaN
BH-A0W4   NaN
BH-A0W7   NaN
BH-A18H   NaN
BH-A18J   NaN
BH-A18M   NaN
BH-A18N   NaN
BH-A18R   NaN
C8-A12K   NaN
C8-A133   NaN
C8-A134   NaN
C8-A135   NaN
C8-A137   NaN
E2-A10A   NaN
E2-A10C   NaN
E2-A14P   NaN
E2-A14Q   NaN
E2-A14S   NaN
E2-A14W   NaN
E2-A14Y   NaN
E2-A152   NaN
E2-A153   NaN
E2-A156   NaN
E2-A15C   NaN
E2-A15L   NaN
E2-A15M   NaN
E2-A576   NaN
E9-A1R6   NaN
Name: cg01637734, dtype: float64
cg09467501
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg09467501, dtype: float64
cg19063972
num of missing rows:  4
patient_id
A8-A0AD   NaN
AC-A6IX   NaN
BH-A0BJ   NaN
BH-A0H0   NaN
Name: cg19063972, dtype: float64
cg14116122
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg14116122, dtype: float64
cg02880679
num of missing rows:  23
patient_id
A2-A0EW   NaN
A2-A0YG   NaN
A7-A0D9   NaN
A8-A08B   NaN
A8-A09G   NaN
AC-A6IX   NaN
AO-A03V   NaN
AO-A126   NaN
AR-A0U3   NaN
AR-A1AH   NaN
B6-A0IH   NaN
B6-A0RH   NaN
BH-A0AY   NaN
BH-A0BR   NaN
BH-A0C1   NaN
BH-A0DZ   NaN
BH-A18J   NaN
BH-A18P   NaN
C8-A135   NaN
C8-A137   NaN
D8-A13Z   NaN
E2-A152   NaN
E2-A15H   NaN
Name: cg02880679, dtype: float64
cg03468463
num of missing rows:  18
patient_id
A1-A0SD   NaN
A7-A0DA   NaN
A8-A06U   NaN
A8-A09D   NaN
AR-A1AV   NaN
B6-A0RH   NaN
BH-A0C7   NaN
BH-A18H   NaN
BH-A18R   NaN
C8-A12P   NaN
C8-A12Q   NaN
C8-A12Z   NaN
C8-A134   NaN
C8-A138   NaN
C8-A1HM   NaN
E2-A14Q   NaN
E2-A152   NaN
E2-A154   NaN
Name: cg03468463, dtype: float64
cg00995065
num of missing rows:  16
patient_id
A2-A0T0   NaN
A2-A0YF   NaN
A2-A0YK   NaN
A2-A4S1   NaN
A7-A4SA   NaN
A7-A5ZX   NaN
AC-A23H   NaN
AC-A2B8   NaN
AC-A4ZE   NaN
AR-A0TR   NaN
AR-A0U2   NaN
BH-A0DH   NaN
BH-A0DS   NaN
BH-A0HB   NaN
C8-A27B   NaN
E2-A9RU   NaN
Name: cg00995065, dtype: float64
cg09137696
num of missing rows:  1
patient_id
BH-A0BS   NaN
Name: cg09137696, dtype: float64
cg23843505
num of missing rows:  3
patient_id
AO-A129   NaN
B6-A0X7   NaN
C8-A134   NaN
Name: cg23843505, dtype: float64
cg13002939
num of missing rows:  2
patient_id
B6-A0RH   NaN
E2-A1L6   NaN
Name: cg13002939, dtype: float64
cg06274159
num of missing rows:  2
patient_id
AO-A03V   NaN
B6-A0RS   NaN
Name: cg06274159, dtype: float64
cg25683185
num of missing rows:  44
patient_id
A2-A04N   NaN
A2-A04W   NaN
A2-A0ES   NaN
A2-A0T3   NaN
A8-A08L   NaN
AO-A03O   NaN
AO-A03V   NaN
AO-A12D   NaN
B6-A0IH   NaN
B6-A0RH   NaN
BH-A0BO   NaN
BH-A0BP   NaN
BH-A0C7   NaN
BH-A0DE   NaN
BH-A0DO   NaN
BH-A0DT   NaN
BH-A0DX   NaN
BH-A0E9   NaN
BH-A0H5   NaN
BH-A18H   NaN
BH-A18J   NaN
BH-A18M   NaN
BH-A18P   NaN
BH-A18U   NaN
BH-A1EV   NaN
C8-A12Q   NaN
C8-A12Y   NaN
C8-A131   NaN
C8-A133   NaN
C8-A134   NaN
D8-A140   NaN
E2-A10A   NaN
E2-A14P   NaN
E2-A14Q   NaN
E2-A14X   NaN
E2-A14Y   NaN
E2-A14Z   NaN
E2-A153   NaN
E2-A155   NaN
E2-A15C   NaN
E2-A15H   NaN
E2-A15L   NaN
E2-A15M   NaN
E2-A15P   NaN
Name: cg25683185, dtype: float64
cg22975913
num of missing rows:  5
patient_id
B6-A0IH   NaN
BH-A18L   NaN
BH-A18P   NaN
BH-A18Q   NaN
C8-A12T   NaN
Name: cg22975913, dtype: float64
cg21604803
num of missing rows:  6
patient_id
A2-A0SU   NaN
A7-A4SB   NaN
AQ-A04L   NaN
BH-A1FG   NaN
BH-A1FM   NaN
D8-A1JI   NaN
Name: cg21604803, dtype: float64
cg22598028
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg22598028, dtype: float64
cg05628549
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg05628549, dtype: float64
cg07748540
num of missing rows:  2
patient_id
D8-A1JH   NaN
E9-A1RF   NaN
Name: cg07748540, dtype: float64
cg16792632
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg16792632, dtype: float64
cg01725199
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg01725199, dtype: float64
cg17525406
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg17525406, dtype: float64
cg24512973
num of missing rows:  4
patient_id
AR-A0TY   NaN
BH-A0HY   NaN
C8-A134   NaN
C8-A137   NaN
Name: cg24512973, dtype: float64
cg07104706
num of missing rows:  2
patient_id
BH-A0DD   NaN
D8-A1JH   NaN
Name: cg07104706, dtype: float64
cg18277754
num of missing rows:  1
patient_id
C8-A134   NaN
Name: cg18277754, dtype: float64
cg22905097
num of missing rows:  1
patient_id
E2-A1L6   NaN
Name: cg22905097, dtype: float64
cg01186777
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg01186777, dtype: float64
cg08009622
num of missing rows:  1
patient_id
B6-A0RH   NaN
Name: cg08009622, dtype: float64
cg22161476
num of missing rows:  2
patient_id
C8-A134   NaN
E2-A155   NaN
Name: cg22161476, dtype: float64
cg12374721
num of missing rows:  4
patient_id
AN-A0XT   NaN
AO-A03V   NaN
BH-A18G   NaN
C8-A134   NaN
Name: cg12374721, dtype: float64
cg19731268
num of missing rows:  4
patient_id
BH-A0BJ   NaN
BH-A0H0   NaN
BH-A0H9   NaN
D8-A73X   NaN
Name: cg19731268, dtype: float64
cg06906435
num of missing rows:  33
patient_id
A2-A0SW   NaN
A2-A0YG   NaN
A2-A0YK   NaN
A7-A13F   NaN
AC-A23H   NaN
AO-A0JF   NaN
AO-A12B   NaN
AQ-A04L   NaN
AR-A1AV   NaN
B6-A0RE   NaN
B6-A0WV   NaN
B6-A0WW   NaN
B6-A0WX   NaN
B6-A0WY   NaN
BH-A0AZ   NaN
BH-A0BW   NaN
BH-A0BZ   NaN
BH-A0C7   NaN
BH-A0DD   NaN
BH-A0WA   NaN
BH-A18T   NaN
BH-A1EU   NaN
BH-A1F0   NaN
BH-A1FM   NaN
C8-A134   NaN
C8-A1HG   NaN
C8-A1HM   NaN
C8-A1HN   NaN
E2-A14Q   NaN
E9-A1N3   NaN
E9-A1RD   NaN
E9-A1RF   NaN
E9-A226   NaN
Name: cg06906435, dtype: float64
cg21553524
num of missing rows:  1
patient_id
D8-A1JH   NaN
Name: cg21553524, dtype: float64
cg06275635
num of missing rows:  6
patient_id
BH-A18J   NaN
C8-A12U   NaN
C8-A130   NaN
C8-A133   NaN
C8-A134   NaN
E2-A14W   NaN
Name: cg06275635, dtype: float64
cg07070934
num of missing rows:  1
patient_id
E2-A1L6   NaN
Name: cg07070934, dtype: float64
cg21309147
num of missing rows:  1
patient_id
B6-A0RI   NaN
Name: cg21309147, dtype: float64
cg12621514
num of missing rows:  32
patient_id
A2-A04W   NaN
A2-A0D3   NaN
A7-A0CJ   NaN
A7-A0DA   NaN
A8-A09Z   NaN
B6-A0RH   NaN
BH-A0AV   NaN
BH-A0BR   NaN
BH-A0BV   NaN
BH-A0C1   NaN

In [14]:
# eliminate na columns
print('cnv before: ', omic_cnv.shape)
omic_cnv = omic_cnv.dropna(axis=1, how='any')
print('cnv after: ', omic_cnv.shape)

print('dna before: ', omic_dna.shape)
omic_dna = omic_dna.dropna(axis=1, how='any')
print('dna after: ', omic_dna.shape)

print('mirna before: ', omic_mirna.shape)
omic_mirna = omic_mirna.dropna(axis=1, how='any')
print('mirna after: ', omic_mirna.shape)

print('mrna before: ', omic_mrna.shape)
omic_mrna = omic_mrna.dropna(axis=1, how='any')
print('mrna after: ', omic_mrna.shape)

cnv before:  (1012, 4096)
cnv after:  (1012, 4096)
dna before:  (845, 4096)
dna after:  (845, 2404)
mirna before:  (1012, 306)
mirna after:  (1012, 191)
mrna before:  (1012, 4096)
mrna after:  (1012, 4096)

In [15]:
# check for na in dna data:
find_na(omic_dna)

columns
num of column with na:  0
patients
size:  0
Empty DataFrame
Columns: [cg22621695, cg25631352, cg08089301, cg12998491, cg12874092, cg06168050, cg04034767, cg04920951, cg07533148, cg14458834, cg08788717, cg17688525, cg16970232, cg13912117, cg18630040, cg04970117, cg02879662, cg26537639, cg18794577, cg03158400, cg22037648, cg02776251, cg13297865, cg12382902, cg26365854, cg11617144, cg21546671, cg14696396, cg11428724, cg26117023, cg15692239, cg23363832, cg09053680, cg16232979, cg18342279, cg27016990, cg14900471, cg17610929, cg08441170, cg11591325, cg08186362, cg21026663, cg25336579, cg01561916, cg23495733, cg21790626, cg07846220, cg13986130, cg05497616, cg06825142, cg14743462, cg24826867, cg23771603, cg26599006, cg20311501, cg00290506, cg27619475, cg08056146, cg09186006, cg07080358, cg04048259, cg14988503, cg11638200, cg20616414, cg06220235, cg04632671, cg19162106, cg03238797, cg14539231, cg19246110, cg26090652, cg02131967, cg14681055, cg09068528, cg08725962, cg00027083, cg13801416, cg17410236, cg16557944, cg04532952, cg05845178, cg14015044, cg12949975, cg12601757, cg04786857, cg25152348, cg26668713, cg22775000, cg04770504, cg09644722, cg21053323, cg27637521, cg12388309, cg26609631, cg15746719, cg23051664, cg11389172, cg13449778, cg01261503, cg21688264, ...]
Index: []

[0 rows x 2404 columns]

In [16]:
# create the signatures
# some columns are duplicated, have the same name across multiple datasets, added a prefix to distinguish them
omic_cnv = omic_cnv.add_prefix('CNV_')
omic_dna = omic_dna.add_prefix('DNA_')
omic_mirna = omic_mirna.add_prefix('miRNA_')
omic_mrna = omic_mrna.add_prefix('mRNA')

sign = {'CNV': omic_cnv.columns.tolist(), 'DNA': omic_dna.columns.tolist(), 'miRNA': omic_mirna.columns.tolist(), 'mRNA': omic_mrna.columns.tolist() }
#print(sign)
max_len = max(len(v) for v in sign.values())
sign = {k: list(v) + [np.nan]*(max_len - len(v)) for k, v in sign.items()}
signatures = pd.DataFrame(sign)

signatures

,CNV,DNA,miRNA,mRNA
0,CNV_ENSG00000140798,DNA_cg22621695,miRNA_hsa-mir-196a-1,mRNAENSG00000110484
1,CNV_ENSG00000261017,DNA_cg25631352,miRNA_hsa-mir-205,mRNAENSG00000124935
2,CNV_ENSG00000288026,DNA_cg08089301,miRNA_hsa-mir-196a-2,mRNAENSG00000160182
3,CNV_ENSG00000260450,DNA_cg12998491,miRNA_hsa-mir-375,mRNAENSG00000159763
4,CNV_ENSG00000261538,DNA_cg12874092,miRNA_hsa-mir-9-2,mRNAENSG00000153002
...,...,...,...,...
4091,CNV_ENSG00000227413,NaN,NaN,mRNAENSG00000136160
4092,CNV_ENSG00000273176,NaN,NaN,mRNAENSG00000158186
4093,CNV_ENSG00000274280,NaN,NaN,mRNAENSG00000231367
4094,CNV_ENSG00000266320,NaN,NaN,mRNAENSG00000276557
4095,CNV_ENSG00000273424,NaN,NaN,mRNAENSG00000275791

In [17]:
#check for na values in dna again
find_na(omic_dna)

columns
num of column with na:  0
patients
size:  0
Empty DataFrame
Columns: [DNA_cg22621695, DNA_cg25631352, DNA_cg08089301, DNA_cg12998491, DNA_cg12874092, DNA_cg06168050, DNA_cg04034767, DNA_cg04920951, DNA_cg07533148, DNA_cg14458834, DNA_cg08788717, DNA_cg17688525, DNA_cg16970232, DNA_cg13912117, DNA_cg18630040, DNA_cg04970117, DNA_cg02879662, DNA_cg26537639, DNA_cg18794577, DNA_cg03158400, DNA_cg22037648, DNA_cg02776251, DNA_cg13297865, DNA_cg12382902, DNA_cg26365854, DNA_cg11617144, DNA_cg21546671, DNA_cg14696396, DNA_cg11428724, DNA_cg26117023, DNA_cg15692239, DNA_cg23363832, DNA_cg09053680, DNA_cg16232979, DNA_cg18342279, DNA_cg27016990, DNA_cg14900471, DNA_cg17610929, DNA_cg08441170, DNA_cg11591325, DNA_cg08186362, DNA_cg21026663, DNA_cg25336579, DNA_cg01561916, DNA_cg23495733, DNA_cg21790626, DNA_cg07846220, DNA_cg13986130, DNA_cg05497616, DNA_cg06825142, DNA_cg14743462, DNA_cg24826867, DNA_cg23771603, DNA_cg26599006, DNA_cg20311501, DNA_cg00290506, DNA_cg27619475, DNA_cg08056146, DNA_cg09186006, DNA_cg07080358, DNA_cg04048259, DNA_cg14988503, DNA_cg11638200, DNA_cg20616414, DNA_cg06220235, DNA_cg04632671, DNA_cg19162106, DNA_cg03238797, DNA_cg14539231, DNA_cg19246110, DNA_cg26090652, DNA_cg02131967, DNA_cg14681055, DNA_cg09068528, DNA_cg08725962, DNA_cg00027083, DNA_cg13801416, DNA_cg17410236, DNA_cg16557944, DNA_cg04532952, DNA_cg05845178, DNA_cg14015044, DNA_cg12949975, DNA_cg12601757, DNA_cg04786857, DNA_cg25152348, DNA_cg26668713, DNA_cg22775000, DNA_cg04770504, DNA_cg09644722, DNA_cg21053323, DNA_cg27637521, DNA_cg12388309, DNA_cg26609631, DNA_cg15746719, DNA_cg23051664, DNA_cg11389172, DNA_cg13449778, DNA_cg01261503, DNA_cg21688264, ...]
Index: []

[0 rows x 2404 columns]

In [18]:
# remove unnamed col if present
if 'Unnamed: 0' in signatures.columns:
    signatures = signatures.drop(columns=['Unnamed: 0'])
    print('dropped')

print(signatures.columns)

Index(['CNV', 'DNA', 'miRNA', 'mRNA'], dtype='object')

In [19]:
# save the new csv
sign_folder = direction + f'/metadata/{study}_signatures.csv'
signatures.to_csv(f'{sign_folder}')

now to the single omic file that contains all the omic data

In [20]:
find_na(omic_dna)

columns
num of column with na:  0
patients
size:  0
Empty DataFrame
Columns: [DNA_cg22621695, DNA_cg25631352, DNA_cg08089301, DNA_cg12998491, DNA_cg12874092, DNA_cg06168050, DNA_cg04034767, DNA_cg04920951, DNA_cg07533148, DNA_cg14458834, DNA_cg08788717, DNA_cg17688525, DNA_cg16970232, DNA_cg13912117, DNA_cg18630040, DNA_cg04970117, DNA_cg02879662, DNA_cg26537639, DNA_cg18794577, DNA_cg03158400, DNA_cg22037648, DNA_cg02776251, DNA_cg13297865, DNA_cg12382902, DNA_cg26365854, DNA_cg11617144, DNA_cg21546671, DNA_cg14696396, DNA_cg11428724, DNA_cg26117023, DNA_cg15692239, DNA_cg23363832, DNA_cg09053680, DNA_cg16232979, DNA_cg18342279, DNA_cg27016990, DNA_cg14900471, DNA_cg17610929, DNA_cg08441170, DNA_cg11591325, DNA_cg08186362, DNA_cg21026663, DNA_cg25336579, DNA_cg01561916, DNA_cg23495733, DNA_cg21790626, DNA_cg07846220, DNA_cg13986130, DNA_cg05497616, DNA_cg06825142, DNA_cg14743462, DNA_cg24826867, DNA_cg23771603, DNA_cg26599006, DNA_cg20311501, DNA_cg00290506, DNA_cg27619475, DNA_cg08056146, DNA_cg09186006, DNA_cg07080358, DNA_cg04048259, DNA_cg14988503, DNA_cg11638200, DNA_cg20616414, DNA_cg06220235, DNA_cg04632671, DNA_cg19162106, DNA_cg03238797, DNA_cg14539231, DNA_cg19246110, DNA_cg26090652, DNA_cg02131967, DNA_cg14681055, DNA_cg09068528, DNA_cg08725962, DNA_cg00027083, DNA_cg13801416, DNA_cg17410236, DNA_cg16557944, DNA_cg04532952, DNA_cg05845178, DNA_cg14015044, DNA_cg12949975, DNA_cg12601757, DNA_cg04786857, DNA_cg25152348, DNA_cg26668713, DNA_cg22775000, DNA_cg04770504, DNA_cg09644722, DNA_cg21053323, DNA_cg27637521, DNA_cg12388309, DNA_cg26609631, DNA_cg15746719, DNA_cg23051664, DNA_cg11389172, DNA_cg13449778, DNA_cg01261503, DNA_cg21688264, ...]
Index: []

[0 rows x 2404 columns]

In [21]:

combined_df = omic_dna.join([omic_cnv, omic_mirna, omic_mrna], how='outer')
combined_df[:3]

,DNA_cg22621695,DNA_cg25631352,DNA_cg08089301,DNA_cg12998491,DNA_cg12874092,DNA_cg06168050,DNA_cg04034767,DNA_cg04920951,DNA_cg07533148,DNA_cg14458834,...,mRNAENSG00000183840,mRNAENSG00000182463,mRNAENSG00000072571,mRNAENSG00000169607,mRNAENSG00000070526,mRNAENSG00000136160,mRNAENSG00000158186,mRNAENSG00000231367,mRNAENSG00000276557,mRNAENSG00000275791
3C-AALI,-3.529280,-1.283741,0.809936,-6.183612,-1.251846,-4.335636,-0.522545,0.211296,-3.474937,2.453824,...,2.904754,1.525016,3.363269,4.270110,1.723034,1.743989,3.610027,0.266037,1.643025,2.842657
3C-AALJ,-3.944544,-1.708141,0.805805,0.074889,-0.404185,-4.618542,1.127364,-0.344821,-5.519056,1.459287,...,2.121745,1.618709,4.345070,3.016514,0.651224,2.384050,4.342299,0.496820,2.081885,2.132478
3C-AALK,-3.093348,-1.532099,0.430924,-0.605442,-1.372814,-1.836377,-0.198532,-1.358223,-0.692899,0.853719,...,2.982145,2.221877,2.876095,2.212289,1.827697,2.520196,3.768692,0.446362,1.842335,1.937570

In [22]:
combined_df[combined_df.index == 'E9-A228']

,DNA_cg22621695,DNA_cg25631352,DNA_cg08089301,DNA_cg12998491,DNA_cg12874092,DNA_cg06168050,DNA_cg04034767,DNA_cg04920951,DNA_cg07533148,DNA_cg14458834,...,mRNAENSG00000183840,mRNAENSG00000182463,mRNAENSG00000072571,mRNAENSG00000169607,mRNAENSG00000070526,mRNAENSG00000136160,mRNAENSG00000158186,mRNAENSG00000231367,mRNAENSG00000276557,mRNAENSG00000275791
E9-A228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.412131,1.601174,5.510886,3.780678,0.430071,3.233044,4.08203,0.204516,0.67717,0.188148

some patients in brca omic dna don't have any data for the dna attributes. Put 0s in their place and deal with it in the model

In [23]:
# checkk dna data
find_na(combined_df)

columns
DNA_cg22621695
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg22621695, Length: 167, dtype: float64
DNA_cg25631352
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg25631352, Length: 167, dtype: float64
DNA_cg08089301
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08089301, Length: 167, dtype: float64
DNA_cg12998491
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg12998491, Length: 167, dtype: float64
DNA_cg12874092
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg12874092, Length: 167, dtype: float64
DNA_cg06168050
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg06168050, Length: 167, dtype: float64
DNA_cg04034767
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04034767, Length: 167, dtype: float64
DNA_cg04920951
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04920951, Length: 167, dtype: float64
DNA_cg07533148
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg07533148, Length: 167, dtype: float64
DNA_cg14458834
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14458834, Length: 167, dtype: float64
DNA_cg08788717
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08788717, Length: 167, dtype: float64
DNA_cg17688525
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg17688525, Length: 167, dtype: float64
DNA_cg16970232
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg16970232, Length: 167, dtype: float64
DNA_cg13912117
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg13912117, Length: 167, dtype: float64
DNA_cg18630040
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg18630040, Length: 167, dtype: float64
DNA_cg04970117
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04970117, Length: 167, dtype: float64
DNA_cg02879662
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg02879662, Length: 167, dtype: float64
DNA_cg26537639
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg26537639, Length: 167, dtype: float64
DNA_cg18794577
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg18794577, Length: 167, dtype: float64
DNA_cg03158400
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg03158400, Length: 167, dtype: float64
DNA_cg22037648
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg22037648, Length: 167, dtype: float64
DNA_cg02776251
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg02776251, Length: 167, dtype: float64
DNA_cg13297865
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg13297865, Length: 167, dtype: float64
DNA_cg12382902
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg12382902, Length: 167, dtype: float64
DNA_cg26365854
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg26365854, Length: 167, dtype: float64
DNA_cg11617144
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg11617144, Length: 167, dtype: float64
DNA_cg21546671
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg21546671, Length: 167, dtype: float64
DNA_cg14696396
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14696396, Length: 167, dtype: float64
DNA_cg11428724
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg11428724, Length: 167, dtype: float64
DNA_cg26117023
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg26117023, Length: 167, dtype: float64
DNA_cg15692239
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg15692239, Length: 167, dtype: float64
DNA_cg23363832
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg23363832, Length: 167, dtype: float64
DNA_cg09053680
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg09053680, Length: 167, dtype: float64
DNA_cg16232979
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg16232979, Length: 167, dtype: float64
DNA_cg18342279
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg18342279, Length: 167, dtype: float64
DNA_cg27016990
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg27016990, Length: 167, dtype: float64
DNA_cg14900471
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14900471, Length: 167, dtype: float64
DNA_cg17610929
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg17610929, Length: 167, dtype: float64
DNA_cg08441170
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08441170, Length: 167, dtype: float64
DNA_cg11591325
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg11591325, Length: 167, dtype: float64
DNA_cg08186362
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08186362, Length: 167, dtype: float64
DNA_cg21026663
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg21026663, Length: 167, dtype: float64
DNA_cg25336579
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg25336579, Length: 167, dtype: float64
DNA_cg01561916
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg01561916, Length: 167, dtype: float64
DNA_cg23495733
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg23495733, Length: 167, dtype: float64
DNA_cg21790626
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg21790626, Length: 167, dtype: float64
DNA_cg07846220
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg07846220, Length: 167, dtype: float64
DNA_cg13986130
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg13986130, Length: 167, dtype: float64
DNA_cg05497616
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg05497616, Length: 167, dtype: float64
DNA_cg06825142
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg06825142, Length: 167, dtype: float64
DNA_cg14743462
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14743462, Length: 167, dtype: float64
DNA_cg24826867
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg24826867, Length: 167, dtype: float64
DNA_cg23771603
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg23771603, Length: 167, dtype: float64
DNA_cg26599006
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg26599006, Length: 167, dtype: float64
DNA_cg20311501
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg20311501, Length: 167, dtype: float64
DNA_cg00290506
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg00290506, Length: 167, dtype: float64
DNA_cg27619475
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg27619475, Length: 167, dtype: float64
DNA_cg08056146
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08056146, Length: 167, dtype: float64
DNA_cg09186006
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg09186006, Length: 167, dtype: float64
DNA_cg07080358
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg07080358, Length: 167, dtype: float64
DNA_cg04048259
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04048259, Length: 167, dtype: float64
DNA_cg14988503
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14988503, Length: 167, dtype: float64
DNA_cg11638200
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg11638200, Length: 167, dtype: float64
DNA_cg20616414
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg20616414, Length: 167, dtype: float64
DNA_cg06220235
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg06220235, Length: 167, dtype: float64
DNA_cg04632671
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04632671, Length: 167, dtype: float64
DNA_cg19162106
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg19162106, Length: 167, dtype: float64
DNA_cg03238797
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg03238797, Length: 167, dtype: float64
DNA_cg14539231
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14539231, Length: 167, dtype: float64
DNA_cg19246110
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg19246110, Length: 167, dtype: float64
DNA_cg26090652
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg26090652, Length: 167, dtype: float64
DNA_cg02131967
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg02131967, Length: 167, dtype: float64
DNA_cg14681055
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg14681055, Length: 167, dtype: float64
DNA_cg09068528
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg09068528, Length: 167, dtype: float64
DNA_cg08725962
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg08725962, Length: 167, dtype: float64
DNA_cg00027083
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg00027083, Length: 167, dtype: float64
DNA_cg13801416
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg13801416, Length: 167, dtype: float64
DNA_cg17410236
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg17410236, Length: 167, dtype: float64
DNA_cg16557944
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg16557944, Length: 167, dtype: float64
DNA_cg04532952
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg04532952, Length: 167, dtype: float64
DNA_cg05845178
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN
MS-A51U   NaN
E9-A54Y   NaN
LL-A6FQ   NaN
EW-A1PC   NaN
Name: DNA_cg05845178, Length: 167, dtype: float64
DNA_cg14015044
num of missing rows:  167
E9-A228   NaN
LL-A5YP   NaN
OL-A66K   NaN
LL-A73Z   NaN
OL-A5RV   NaN
           ..
EW-A1OW   NaN

In [24]:
# find all na values in omic_dna and change the value from na to 0
combined_df = combined_df.fillna(0)

In [25]:
# change the index
combined_df.index = to_case_id(combined_df.index)
if 'Unnamed: 0' in combined_df.columns:
    combined_df = combined_df.drop(columns=['Unnamed: 0'])
    print('dropped')

print(combined_df.columns)
combined_df.head(3)

Index(['DNA_cg22621695', 'DNA_cg25631352', 'DNA_cg08089301', 'DNA_cg12998491',
       'DNA_cg12874092', 'DNA_cg06168050', 'DNA_cg04034767', 'DNA_cg04920951',
       'DNA_cg07533148', 'DNA_cg14458834',
       ...
       'mRNAENSG00000183840', 'mRNAENSG00000182463', 'mRNAENSG00000072571',
       'mRNAENSG00000169607', 'mRNAENSG00000070526', 'mRNAENSG00000136160',
       'mRNAENSG00000158186', 'mRNAENSG00000231367', 'mRNAENSG00000276557',
       'mRNAENSG00000275791'],
      dtype='object', length=10787)

,DNA_cg22621695,DNA_cg25631352,DNA_cg08089301,DNA_cg12998491,DNA_cg12874092,DNA_cg06168050,DNA_cg04034767,DNA_cg04920951,DNA_cg07533148,DNA_cg14458834,...,mRNAENSG00000183840,mRNAENSG00000182463,mRNAENSG00000072571,mRNAENSG00000169607,mRNAENSG00000070526,mRNAENSG00000136160,mRNAENSG00000158186,mRNAENSG00000231367,mRNAENSG00000276557,mRNAENSG00000275791
TCGA-3C-AALI,-3.529280,-1.283741,0.809936,-6.183612,-1.251846,-4.335636,-0.522545,0.211296,-3.474937,2.453824,...,2.904754,1.525016,3.363269,4.270110,1.723034,1.743989,3.610027,0.266037,1.643025,2.842657
TCGA-3C-AALJ,-3.944544,-1.708141,0.805805,0.074889,-0.404185,-4.618542,1.127364,-0.344821,-5.519056,1.459287,...,2.121745,1.618709,4.345070,3.016514,0.651224,2.384050,4.342299,0.496820,2.081885,2.132478
TCGA-3C-AALK,-3.093348,-1.532099,0.430924,-0.605442,-1.372814,-1.836377,-0.198532,-1.358223,-0.692899,0.853719,...,2.982145,2.221877,2.876095,2.212289,1.827697,2.520196,3.768692,0.446362,1.842335,1.937570

In [26]:
# check for na values
find_na(combined_df)

columns

num of column with na:  0
patients
size:  0
Empty DataFrame
Columns: [DNA_cg22621695, DNA_cg25631352, DNA_cg08089301, DNA_cg12998491, DNA_cg12874092, DNA_cg06168050, DNA_cg04034767, DNA_cg04920951, DNA_cg07533148, DNA_cg14458834, DNA_cg08788717, DNA_cg17688525, DNA_cg16970232, DNA_cg13912117, DNA_cg18630040, DNA_cg04970117, DNA_cg02879662, DNA_cg26537639, DNA_cg18794577, DNA_cg03158400, DNA_cg22037648, DNA_cg02776251, DNA_cg13297865, DNA_cg12382902, DNA_cg26365854, DNA_cg11617144, DNA_cg21546671, DNA_cg14696396, DNA_cg11428724, DNA_cg26117023, DNA_cg15692239, DNA_cg23363832, DNA_cg09053680, DNA_cg16232979, DNA_cg18342279, DNA_cg27016990, DNA_cg14900471, DNA_cg17610929, DNA_cg08441170, DNA_cg11591325, DNA_cg08186362, DNA_cg21026663, DNA_cg25336579, DNA_cg01561916, DNA_cg23495733, DNA_cg21790626, DNA_cg07846220, DNA_cg13986130, DNA_cg05497616, DNA_cg06825142, DNA_cg14743462, DNA_cg24826867, DNA_cg23771603, DNA_cg26599006, DNA_cg20311501, DNA_cg00290506, DNA_cg27619475, DNA_cg08056146, DNA_cg09186006, DNA_cg07080358, DNA_cg04048259, DNA_cg14988503, DNA_cg11638200, DNA_cg20616414, DNA_cg06220235, DNA_cg04632671, DNA_cg19162106, DNA_cg03238797, DNA_cg14539231, DNA_cg19246110, DNA_cg26090652, DNA_cg02131967, DNA_cg14681055, DNA_cg09068528, DNA_cg08725962, DNA_cg00027083, DNA_cg13801416, DNA_cg17410236, DNA_cg16557944, DNA_cg04532952, DNA_cg05845178, DNA_cg14015044, DNA_cg12949975, DNA_cg12601757, DNA_cg04786857, DNA_cg25152348, DNA_cg26668713, DNA_cg22775000, DNA_cg04770504, DNA_cg09644722, DNA_cg21053323, DNA_cg27637521, DNA_cg12388309, DNA_cg26609631, DNA_cg15746719, DNA_cg23051664, DNA_cg11389172, DNA_cg13449778, DNA_cg01261503, DNA_cg21688264, ...]
Index: []

[0 rows x 10787 columns]

In [27]:
# remove all na columns
#print('before: ', combined_df.shape)
#combined_df = combined_df.dropna(axis=1, how='any')
#print('after: ', combined_df.shape)

#find_na(combined_df)

In [28]:
omic_folder = direction + f'/raw_rna_data/other/{study}/rna_clean.csv'
combined_df.to_csv(f'{omic_folder}')